version: 2.1

jobs:
  test:
    working_directory: ~/repository
    docker:
      - image: circleci/node:10.16.3
    steps:
      - checkout
      - run:
          name: update-npm
          command: 'sudo npm install -g npm@latest'
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: install-npm
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: test
          command: npm run test-nowatch

  build:
    machine: true
    working_directory: ~/repository
    steps:
      - checkout
      - run: echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
      - run: echo "$CIRCLE_SHA1" > .version
      - run: docker build . -t $DOCKER_IMAGE:latest
      - run: docker push $DOCKER_IMAGE:latest
      - run: docker tag $DOCKER_IMAGE:latest $DOCKER_IMAGE:$CIRCLE_SHA1
      - run: docker push $DOCKER_IMAGE:$CIRCLE_SHA1
      - run: echo "Docker build made sucessfully!! for $CIRCLE_SHA1"

  deploy:
      machine: true
      steps:
        - checkout
        - run: sudo apt-get update
        - run: sudo apt-get install -y awscli
        - run: export AWS_ACCESS_KEY_ID="$AWS_ACCESS_KEY_ID"; export AWS_SECRET_ACCESS_KEY="$AWS_SECRET_ACCESS_KEY";
        - run: echo "$CIRCLE_SHA1" > .version
        - run: zip -r deployment-${CIRCLE_SHA1}.zip .
        - run: aws s3 cp deployment-${CIRCLE_SHA1}.zip s3://test-docker-react-app --region $AWS_EBS_REGION
        - run: aws elasticbeanstalk create-application-version --application-name $AWS_EBS_APP --version-label ${CIRCLE_SHA1} --source-bundle S3Bucket="test-docker-react-app",S3Key="deployment-${CIRCLE_SHA1}.zip" --region $AWS_EBS_REGION
        - run: aws elasticbeanstalk update-environment --application-name $AWS_EBS_APP --environment-name $AWS_EBS_ENV --version-label ${CIRCLE_SHA1} --region $AWS_EBS_REGION


workflows:
  version: 2
  test-build-deploy:
    jobs:
      - test
      - build:
          requires:
            - test
          filters:
            branches:
              only: master
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master